### ISSUE TITLE
Any plans for `newtype-derive-2018`?

### ISSUE THREAD

**Issue by EndilWayfare** [A1-Triard/enum-derive-2018#1]
Love for the other workspace member of https://github.com/DanielKeep/rust-custom-derive? It depends on a yanked version of `rustc_version`. Not sure how long ago the yank happened, because my existing crates' `Cargo.lock`s shielded me until now. It shouldn't even be necessary in the 2018 edition, since it's checking for Rust 1.8.

**Comment by A1-Triard** [comment]
I think I'll do it by summer.

**Comment by EndilWayfare** [comment]
Is there anything I can do to help? I'd love to contribute if that would be useful.

**Comment by A1-Triard** [comment]
Done as a first approximation: https://github.com/A1-Triard/newtype-derive-2018

@EndilWayfare , it will be great if you test the result. If everything goes well, then I will publish the crate.
